import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{width: "100vw", height: "100vh", background: "light_blue", paddingTop: "15vh", textAlign: "center"}} className={inter.className}>
        <nav style={{width: "100vw", height: "10vh", background: "navy", display: "flex", flexDirection: "row", justifyContent: "space-evenly", alignItems: "center", position: "fixed", top: "0", left: "0", zIndex: "100"}}>
        <Link href="/">Home</Link>
        <Link href="/articles">Articles</Link>
        <Link href="/posts">Posts</Link>
        </nav>
        {children}
        </body>
    </html>
  )
}
